name: goreleaser-tag

on:
  push:
    tags:        
      - '*' 

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 'latest'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir -p output-apt-repo/orion-backbone/
      # Download the current apt repository
      - uses: actions/checkout@v4
        with:
          repository: Orion-network-dev/apt-registry
          path: output-apt-repo/orion-backbone/
      - run: cp dist/orion*.deb output-apt-repo/orion-backbone/
      - name: Pushes to the apt repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_APT_GITHUB }}
        with:
          source-directory: 'output-apt-repo/orion-backbone'
          destination-github-username: 'Orion-network-dev'
          destination-repository-name: 'apt-registry'
          user-email: 'orion+backbone@mpgn.dev'
          target-branch: main
