name: goreleaser-tag

on:
  push:
    tags:        
      - '*' 

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 'latest'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_APT_GITHUB }}
        with:
          source_file: 'dist/orion_*.deb'
          destination_repo: 'Orion-network-dev/apt-registry'
          destination_folder: 'orion-backbone'
          user_email: 'orion+backbone@mpgn.dev'
          user_name: 'Orion-Backbone Release'
          commit_message: 'Bump the orion-backbone deb file'
          use_rsync: 1